"""empty message

Revision ID: 05beacd54669
Revises: b4201518010d
Create Date: 2020-12-01 14:39:34.025191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05beacd54669'
down_revision = 'b4201518010d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('description', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
